export const workflowAssets = [
  {
    id: 'flova-queue-fast-path',
    title: 'Flova 前端队列三门禁快路径',
    status: '已审核',
    visibility: '内部',
    role: '短视频运营',
    assetType: 'SOP',
    tools: ['Codex', 'Flova', 'Chrome', 'Feishu'],
    tasks: ['视频素材生成', '页面自动化止损'],
    outcomes: ['手动接管文件', '待人工验收下载'],
    painPoints: ['Flova 页面超时', '重复读取项目浪费时间', '页面状态文本滞后'],
    tags: ['Flova', '矩阵号', '快路径', '三门禁'],
    summary: '从 latest.json 和 run JSON 出发，按 Queue gate、Eligibility gate、Flova gate 推进，减少重复读代码和重度浏览器排查。',
    inputs: ['outputs/flova-runs/latest.json', 'run JSON 中的 flovaPrompt', '账号表达记忆'],
    workflow: [
      'Queue gate：先读取 latest.json 和被引用的 run JSON。',
      'Eligibility gate：只检查目标账号是否满足生产条件和表达记忆约束。',
      'Flova gate：只对 ready 项做一次轻量 prompt 粘贴、提交和最小状态确认。',
      '首次 Chrome/Flova 交互超时后，保存手动提示文件并标记需人工介入。',
    ],
    failureModes: ['Chrome/Flova 首次轻量交互超时后不继续重试截图、DOM 和坐标路径。'],
    boundary: '默认停在视频素材或可预览状态，不自动下载，不替代人工验收。',
    feishuFields: ['日期', '账号', '每日视频序号', '生产状态', '下载/验收状态', '手动接管文件'],
    updatedAt: '2026-06-07',
    owner: '李忆超',
  },
  {
    id: 'daily-video-task-generator',
    title: '每日视频任务生成与飞书写入前预检',
    status: '已审核',
    visibility: '内部',
    role: '矩阵号运营',
    assetType: '脚本',
    tools: ['Codex', 'Node.js', 'Feishu'],
    tasks: ['每日任务生成', '飞书同步预检'],
    outcomes: ['待写入任务清单', '网络阻塞提示'],
    painPoints: ['Feishu 网络不可达', '低配额同步失败', '任务状态边界混乱'],
    tags: ['Feishu', '每日任务', '预检', '低配额'],
    summary: '先 dry-run 生成任务，再按网络、凭证、字段结构拆分阻塞原因，避免在飞书不可达时误判脚本逻辑。',
    inputs: ['日期', '热点驱动账号配置', 'Feishu 多维表格字段'],
    workflow: [
      '先执行 dry-run，确认当天任务候选和账号筛选结果。',
      '只处理生产模式为热点驱动且进入热点池的账号。',
      '写入前先判断 open.feishu.cn 是否可达。',
      '网络不可用时输出友好提示，保留本地验证结果，不进行 live read/write。',
    ],
    failureModes: ['DNS 或网络不可达时不要继续调试凭证和字段结构。'],
    boundary: '不能凭旧导出猜测当天 Feishu 记录；网络恢复后重新执行同一路径。',
    feishuFields: ['日期', '账号', '每日视频序号', '剧情目标', '镜头结构', 'Flova生成指令'],
    updatedAt: '2026-06-03',
    owner: '李忆超',
  },
  {
    id: 'account-expression-memory-loop',
    title: '账号表达记忆闭环',
    status: '已审核',
    visibility: '内部',
    role: '矩阵号运营',
    assetType: '岗位方法',
    tools: ['Codex', 'Markdown', 'Flova'],
    tasks: ['账号定位复用', '提示词防漂移'],
    outcomes: ['账号表达约束', '质量复盘记录'],
    painPoints: ['提示词越跑越散', '账号疲劳点没有沉淀', '复盘不进入下一轮执行'],
    tags: ['账号记忆', 'Flova', '质量闭环'],
    summary: '每次执行前读取账号表达记忆，执行后把质量、定位、提示词、审核风险和边界观察写回同一位置。',
    inputs: ['docs/账号表达记忆.md', '本轮 Flova 执行结果', '人工验收意见'],
    workflow: [
      '执行前读取目标账号的表达记忆。',
      '把记忆翻译成具体的写作约束、禁用点和停止边界。',
      '执行后写回本轮观察，尤其是疲劳点、提示词漂移和审核风险。',
      '下一轮任务必须先读取更新后的记忆。',
    ],
    failureModes: ['如果只写一次性提示词而不回写记忆，下一轮会重复踩坑。'],
    boundary: '只写和未来生产质量直接相关的观察，不把无关聊天记录塞进账号记忆。',
    feishuFields: ['账号', '表达约束', '禁用点', '质量观察', '审核风险', '生产边界'],
    updatedAt: '2026-06-02',
    owner: '李忆超',
  },
  {
    id: 'weekly-report-polish',
    title: '运营周报飞书汇报措辞',
    status: '已审核',
    visibility: '内部',
    role: '运营管理',
    assetType: '提示词包',
    tools: ['Codex', 'Feishu'],
    tasks: ['周报整理', '汇报措辞'],
    outcomes: ['可粘贴周报', '周二到周一排期表'],
    painPoints: ['目标不够数字化', '复盘不够像结论', '规划没有排期'],
    tags: ['周报', '飞书', '汇报', '排期'],
    summary: '把目标写成数字，把复盘写成结论，把规划写成排期，输出能直接粘贴进飞书的中文版本。',
    inputs: ['本周工作记录', '下周规划', '已有飞书表格结构'],
    workflow: [
      '先把目标改成可衡量数字。',
      '再把复盘压缩成结论，不写流水账。',
      '最后把下周事项补成周二到周一的排期表。',
    ],
    failureModes: ['业务数字缺失时标出缺口，不虚构结果。'],
    boundary: '不替团队承诺未经确认的目标和日期。',
    feishuFields: ['本周目标', '完成情况', '复盘结论', '下周规划', '负责人'],
    updatedAt: '2026-06-02',
    owner: '李忆超',
  },
  {
    id: 'japan-matrix-audience-gate',
    title: '日本矩阵号剧情前置判断门',
    status: '已审核',
    visibility: '内部',
    role: '剧情号运营',
    assetType: 'SOP',
    tools: ['Codex', 'Flova'],
    tasks: ['剧情方向判断', '受众情绪判断'],
    outcomes: ['剧情方向建议', '停止点确认'],
    painPoints: ['直接写剧情导致方向偏', '没有先判断受众和情绪钩子'],
    tags: ['日本矩阵号', '剧情', '受众判断'],
    summary: '新剧情生成前先判断受众、情绪钩子、节奏和表达方式，确认方向后再进入正式剧情。',
    inputs: ['近期成功案例', '账号定位', '目标主题'],
    workflow: [
      '先阅读近期成功案例和用户既有执行方式。',
      '判断受众、剧情方向、情绪钩子和节奏。',
      '在判断阶段停止，等待用户确认是否继续写正式剧情。',
    ],
    failureModes: ['跳过前置判断会导致格式和节奏不贴合已有 SOP。'],
    boundary: '用户没有明确要求继续时，不直接生成完整剧情。',
    feishuFields: ['账号', '主题', '受众判断', '剧情方向', '是否进入剧情生成'],
    updatedAt: '2026-05-29',
    owner: '李忆超',
  },
  {
    id: 'capcut-edit-decision-list',
    title: '教程脚本转剪映执行清单',
    status: '已审核',
    visibility: '内部',
    role: '教程内容运营',
    assetType: 'SOP',
    tools: ['Codex', '剪映', 'CapCut'],
    tasks: ['教程剪辑规划', '字幕和重点标注'],
    outcomes: ['剪辑决策表', '字幕检查清单'],
    painPoints: ['录屏素材没有剪辑路径', '字幕断句影响理解'],
    tags: ['剪映', '教程', '字幕', 'EDL'],
    summary: '把教程脚本拆成时间线、屏幕动作、字幕、强调点和导出检查项，交给剪辑阶段使用。',
    inputs: ['教程脚本', '录屏素材列表', '目标平台'],
    workflow: [
      '按章节拆分脚本和屏幕动作。',
      '标记缩放点、重点框选、字幕断句和音效时机。',
      '输出剪映可照着执行的编辑决策清单。',
    ],
    failureModes: ['没有素材文件名时先用占位名，剪辑前再替换。'],
    boundary: '不替代最终人工观感检查。',
    feishuFields: ['选题', '脚本链接', '素材状态', '剪辑清单', '字幕状态'],
    updatedAt: '2026-05-28',
    owner: '李忆超',
  },
  {
    id: 'codex-skill-retrospective',
    title: '任务完成后沉淀流程最优解 Skill',
    status: '已审核',
    visibility: '内部',
    role: '运营全员',
    assetType: 'Skill 草稿',
    tools: ['Codex', 'Feishu'],
    tasks: ['任务复盘', 'Skill 草稿生成'],
    outcomes: ['SKILL.md 草稿', '岗位复用说明'],
    painPoints: ['一次性任务没有沉淀', '同事不知道怎么复用 Codex 方法'],
    tags: ['Codex', 'Skill', '复盘', '沉淀'],
    summary: '任务完成后，让 Codex 把真实执行步骤、输入输出、卡点、人工边界整理成可审核的 skill 草稿。',
    inputs: ['任务目标', '执行记录', '最终产出', '失败和止损点'],
    workflow: [
      '让 Codex 回顾本次任务的输入、执行路径、验证方式和产出。',
      '按工作流资产字段补齐岗位、工具、任务、卡点、边界。',
      '生成 SKILL.md 草稿，但先进入人工审核。',
    ],
    failureModes: ['不得把账号、路径、凭证或客户信息直接写进公开草稿。'],
    boundary: 'Skill 草稿必须经审核人确认后才能进入内部可安装区。',
    feishuFields: ['资产标题', '岗位', '工具', '卡点', '复用步骤', '是否可生成Skill', '审核状态'],
    updatedAt: '2026-06-08',
    owner: '李忆超',
  },
  {
    id: 'ops-asset-redaction-review',
    title: '运营工作流资产投稿脱敏审核清单',
    status: '已审核',
    visibility: '内部',
    role: '运营管理',
    assetType: 'SOP',
    tools: ['Codex', '人工审核', '资产库'],
    tasks: ['投稿审核', '敏感信息检查'],
    outcomes: ['脱敏建议', '发布判断'],
    painPoints: ['账号或 token 误发布', '客户信息进入正式资产库', '审核边界不清楚'],
    tags: ['审核', '脱敏', '安全', '投稿池'],
    summary: '发布前用 Codex 辅助检查投稿里是否包含凭证、客户信息、私有路径和未授权链接，管理员确认后再发布。',
    inputs: ['待审核投稿内容', '工具或链接', '贡献人补充说明'],
    workflow: [
      '先让 Codex 按字段检查标题、岗位、痛点、输入、步骤、输出和人工边界。',
      '再检查账号、密码、token、客户信息、公司私有路径和未授权链接。',
      '发现疑似敏感信息时标记为需补充，不进入正式资产库。',
      '管理员只发布已脱敏、边界清楚、能被同事复用的资产。',
    ],
    failureModes: ['审核只看是否有用而不查敏感信息，会让内部资产库承担误发布风险。'],
    boundary: 'Codex 只给审核建议；最终发布、退回或拒绝必须由管理员确认。',
    feishuFields: ['资产标题', '敏感信息标记', '审核结论', '需补充内容', '发布人'],
    updatedAt: '2026-06-09',
    owner: '李忆超',
    primaryCategory: '工作 SOP',
    skillPath: 'skills/ops-asset-redaction-review/SKILL.md',
  },
  {
    id: 'ops-retrospective-to-weekly-plan',
    title: '活动/内容运营选题复盘转下周排期',
    status: '已审核',
    visibility: '内部',
    role: '内容运营',
    assetType: '提示词包',
    tools: ['Codex', 'Feishu'],
    tasks: ['复盘整理', '下周排期'],
    outcomes: ['选题方向', '执行排期表', '待补数字清单'],
    painPoints: ['复盘像流水账', '反馈不能变成排期', '下周动作没有负责人和时间'],
    tags: ['复盘', '排期', '内容运营', '活动运营'],
    summary: '把本周数据、反馈和问题整理成下周选题、动作、负责人和时间表；缺数字时明确标缺口，不虚构。',
    inputs: ['本周数据', '用户反馈', '问题记录', '下周资源约束'],
    workflow: [
      '先把本周结果分成有效动作、无效动作和不确定动作。',
      '把可复用结论转成下周选题或活动动作。',
      '按负责人、时间、输入材料和验收口径排成表。',
      '缺少业务数字时列为待补，不替团队编结果。',
    ],
    failureModes: ['只润色复盘文字，不转成下一周可执行事项。'],
    boundary: 'Codex 不替团队承诺未经确认的日期、负责人、预算和业务结果。',
    feishuFields: ['本周结论', '下周选题', '负责人', '排期', '待补数据', '验收口径'],
    updatedAt: '2026-06-09',
    owner: '李忆超',
    primaryCategory: '提示词包',
    skillPath: 'skills/ops-retrospective-to-weekly-plan/SKILL.md',
  },
  {
    id: 'feishu-schema-change-checklist',
    title: 'Feishu 多维表格字段变更前检查与回滚记录',
    status: '已审核',
    visibility: '内部',
    role: '运营自动化负责人',
    assetType: '自动化流程',
    tools: ['Codex', 'Feishu', 'Node.js'],
    tasks: ['字段变更预检', '回滚记录'],
    outcomes: ['影响范围清单', '回滚说明', '验证步骤'],
    painPoints: ['字段改名导致脚本失效', '状态选项漂移', '没有回滚记录'],
    tags: ['Feishu', '字段', '回滚', '自动化'],
    summary: '改飞书字段前先让 Codex 检查脚本、文档、状态边界和测试影响，改完后记录回滚方式。',
    inputs: ['拟变更字段', '相关脚本路径', '表格字段截图或导出', '当前状态选项'],
    workflow: [
      '列出字段名、字段类型、选项值和使用位置。',
      '搜索脚本、文档和测试中依赖该字段的地方。',
      '生成变更前检查、变更后验证和回滚记录。',
      '负责人确认后再改线上字段。',
    ],
    failureModes: ['直接改线上字段，导致同步脚本和状态判断一起失效。'],
    boundary: 'Codex 可以生成检查清单和影响分析，但不能自行修改线上飞书表结构。',
    feishuFields: ['字段名', '变更原因', '影响脚本', '验证结果', '回滚方式', '负责人'],
    updatedAt: '2026-06-09',
    owner: '李忆超',
    primaryCategory: '自动化流程',
    skillPath: 'skills/feishu-schema-change-checklist/SKILL.md',
  },
  {
    id: 'unreviewed-public-export',
    title: '公开版导出候选池',
    status: '待审核',
    visibility: '内部',
    role: '运营管理',
    assetType: '岗位方法',
    tools: ['Codex'],
    tasks: ['脱敏导出'],
    outcomes: ['公开版候选'],
    painPoints: ['敏感信息误公开'],
    tags: ['二阶段'],
    summary: '二阶段才进入公开站，不在第一版展示。',
    inputs: [],
    workflow: [],
    failureModes: [],
    boundary: '',
    feishuFields: [],
    updatedAt: '2026-06-08',
    owner: '待定',
  },
];

export const syncState = {
  source: '飞书多维表格',
  approvedCount: workflowAssets.filter((asset) => asset.status === '已审核').length,
  pendingCount: workflowAssets.filter((asset) => asset.status !== '已审核').length,
  lastSync: '2026-06-08 18:30',
};
